[package]
name = "pine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "^7.1.1"
clap = "~2.31.2"
rustyline = "9.1.2"
rustyline-derive = "0.6.0"